#pragma once

//Error code ID's for the CLI render application

#define CLI_ERRORCODE___OK 0

#define CLI_ERRORCODE___HELP_PRINTED 1

#define CLI_ERRORCODE___MISSING_ARGUMENT 10
#define CLI_ERRORCODE___INVALID_ARGUMENT 11

#define CLI_ERRORCODE___NO_SCENE 100
#define CLI_ERRORCODE___SCENE_NOT_FOUND 101
#define CLI_ERRORCODE___INVALID_SCENE 102
#define CLI_ERRORCODE___NO_CAMERA_IN_SCENE 103

#define CLI_ERRORCODE___SDL_ERROR 200
